checks:
    php:
        code_rating: true
        duplication: true
tools:
    php_code_coverage:
        enabled: true
    external_code_coverage:
        timeout: 600
build:
    nodes:
        analysis:
            before_commands:
                - composer self-update --2
            tests:
                override: [php-scrutinizer-run]
